# Created with Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: eza-community.eza
PackageVersion: 0.12.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: eza.exe
UpgradeBehavior: install
ReleaseDate: 2023-09-19
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/eza-community/eza/releases/download/v0.12.0/eza.exe_x86_64-pc-windows-gnu.zip
  InstallerSha256: 9a5c02d233e08f9038ea1b5e8ff32839f77aadd9f8881061cdfb9abc4c31eb62
ManifestType: installer
ManifestVersion: 1.5.0
